language: node_js

node_js:
# - "0.12"
- "4.1"
- "4.2"
- "5.0"

before_script:
- npm i -g codeclimate-test-reporter
- npm i -g istanbul

script:
- istanbul cover -x '**/vendor/**' ./node_modules/.bin/_mocha

after_script:
- codeclimate-test-reporter < coverage/lcov.info

env:
- NODE_ENV=test"
